### ISSUE TITLE
Feature request: Max Buy and Max Sell

### ISSUE THREAD

**Issue by nunoarruda** [binance/binance-connector-typescript#39]
The user-facing UI includes a feature where the amount is automatically calculated when setting a price:

<img width="339" alt="max-buy-sell" src="https://github.com/user-attachments/assets/1e9fe7cf-0da9-4fb8-ae37-0187228905bc">

Is there any chance that the Binance API or Binance libraries can implement this feature?

Thanks in advance 👍

**Comment by alplabin** [comment]
Hey,
The Binance library serves as a software package to help users integrate Binance APIs into their projects. Since the feature you’ve requested isn’t part of the Binance APIs, it unfortunately cannot be added to the library.

However, I would suggest writing a custom script using the existing Binance API to calculate the maximum Buy and Sell amounts. You can use the [Account Information](https://developers.binance.com/docs/binance-spot-api-docs/rest-api#account-information-user_data) API to retrieve your balance for the calculation. (TypeScript library: https://github.com/binance/binance-connector-typescript/blob/main/src/modules/restful/trade/trade.ts#L518)
